"""add action

Revision ID: bd5b3db96b02
Revises: 460c09e7b51f
Create Date: 2025-03-05 18:48:36.576640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5b3db96b02'
down_revision = '460c09e7b51f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_items', 'action')
    # ### end Alembic commands ###
