"""add task items

Revision ID: c18ead99cdb8
Revises: 3033138c586e
Create Date: 2025-02-11 12:31:27.784253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18ead99cdb8'
down_revision = '3033138c586e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('kilocalories_per100g', sa.Integer(), nullable=True),
    sa.Column('proteins_per100g', sa.Integer(), nullable=True),
    sa.Column('fats_per100g', sa.Integer(), nullable=True),
    sa.Column('carbohydrates_per100g', sa.Integer(), nullable=True),
    sa.Column('fiber_per100g', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_items_id'), 'task_items', ['id'], unique=False)
    op.drop_column('tasks', 'fiber_per100g')
    op.drop_column('tasks', 'fats_per100g')
    op.drop_column('tasks', 'kilocalories_per100g')
    op.drop_column('tasks', 'carbohydrates_per100g')
    op.drop_column('tasks', 'proteins_per100g')
    op.drop_column('tasks', 'weight')
    op.drop_column('tasks', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('proteins_per100g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('carbohydrates_per100g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('kilocalories_per100g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fats_per100g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fiber_per100g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_items_id'), table_name='task_items')
    op.drop_table('task_items')
    # ### end Alembic commands ###
